import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import NavLink from "@/components/NavLink";
import AnimatedBackground from "@/components/AnimatedBackground";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-900`}
      >
        <AnimatedBackground />
        <div className="relative z-10 min-h-screen text-slate-900">
          <header className="flex flex-col sm:flex-row sm:items-center sm:justify-between px-4 py-4 sm:px-10 sm:py-6 text-sm gap-4 bg-white shadow-sm">
            <Link href="/" className="flex items-center gap-3">
              <Image
                src="/logo.png"
                alt="Billy logo"
                width={100}
                height={100}
                className="rounded w-20 h-auto sm:w-auto sm:h-auto"
              />
            </Link>
            <nav className="flex gap-3 sm:gap-6 flex-wrap justify-center">
              <NavLink href="/items">Items</NavLink>
              <NavLink href="/customers">Customers</NavLink>
              <NavLink href="/invoices">Invoices</NavLink>
            </nav>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
